### ISSUE TITLE
LDAP bind password stored in plain text in Omeka database

### ISSUE THREAD

**Issue by lfarrell** [BGSU-LITS/omeka-plugin-CentralAuth#1]
If values for ldap username and password aren't specified.  It saves the superuser's username and password to the Omeka options table as plaintext. This seems like a security vulnerability.

Dean

**Comment by kloor** [comment]
I can't seem to duplicate this issue on our server. We use the plugin without specifying a username and password for the LDAP server, and the fields are blank within our database.

I've mainly tested this plugin with Omeka 2.2.2. Which version of Omeka are you using?

Do you use a password manager or form autocompletion software? I'm wondering if maybe the fields got filled in because of how they are named. Currently, they do not explicitly turn off autocomplete, so I'll plan to add that in the next version.

Otherwise, did anything odd happen while you were configuring the plugin? Did you have to log in while loading or submitting the plugin page?

**Comment by lfarrell** [comment]
@kloor I don't think auto complete is on.  I'm using Omeka 2.2.2 as well.  I'm already logged in when I configure the plugin, so it doesn't ask me to login again when saving or configuring. I can save the form without a username and password, but if I then go back to edit the settings my LDAP username and password are there.  This seems to happen on my local setup MAMP and on our actual servers. Multiple staff here have tried with the same results.

**Comment by kloor** [comment]
I've entered a username and password on our system and saved it. I then returned and deleted the username and password, and saved again. The fields are empty in our database, and do not reappear when I load the configuration form. 

The same code is used to update all of the options for the plugin, so maybe we can track down if the issue is with those fields or Omeka's plugin options code. If you delete the contents of one of the other fields, save and return to the configuration page, do the contents for that other field reappear?

Which versions of PHP and MySQL are you using?

**Comment by lfarrell** [comment]
Hmm, it does seem to save an empty username and password if I remember to remove them each time I edit the form.  Getting a different, TLS related, error now if I check the TLS box:

authentication failed: 0x1 (Operations error; 00000000: LdapErr: DSID-0C090EDF, comment: TLS or SSL already in effect,

**Comment by lfarrell** [comment]
Trying it in a different browser doesn't seem to have the username and password auto populating. So it looks like your correct that it's something particular to our setup.  If I add one the the plaintext issue is still there however.

**Comment by kloor** [comment]
Which browser/operating system is the reappearance problem occurring in? Maybe it is a browser bug.

I'm not certain about the best approach to encrypting the LDAP password before storing it in the database. I can't hash it like Omeka does with user passwords, as it needs to be retrievable to be sent to the LDAP server. (Omeka's password hashing mechanism also does not look very secure.) Do you have any thoughts about how to obtain and store an encryption key for the password field?

If you check the Use StartTLS box, the host configuration is different than the old LDAP plugin. You should only specify the LDAP server's hostname without any protocol, i.e. ldap.example.com, and you can probably leave the port blank. If you leave Host as ldaps://ldap.example.code, don't check the Use StartTLS box and you'll have to specify the port as 636.

**Comment by lfarrell** [comment]
Hmm setting it that way gives:  "In order to perform this operation a successful bind must be completed on the connection" whether I check the bind DN or not.

Our setup doesn't actually require binding or default credentials.  

The password issue is a tough one. Maybe it could be save as an environment variable on the server. Not sure if that would work on Windows though.
Maybe another option is to save it to text file, which would ideally sit outside the web root, though you'd need write permissions wherever that file should end up. Maybe another field in the config form to specify a writable directory to save the file too.

I know newer versions of PHP have some nice encryption methods, but of course you still need the raw password somewhere for LDAP.

**Comment by kloor** [comment]
Logging in through LDAP actually uses the username and password you specify to bind to their user in the directory. That error message may be because the Base DN or the Account Filter Format settings are incorrect for your LDAP server.

For our server, I had to set the Base DN as ou=people,dc=bgsu,dc=edu and the Account Filter Format as uid=%s for our LDAP server to work. I'm pretty sure our LDAP server is part of Active Directory. Your LDAP server administrator may know what the correct values for each of those fields would be.

**Comment by kloor** [comment]
Encrypting the password does sound like it would be very complex to implement. I'm also not entirely certain if the username and password for LDAP would actually be of any use. I think they are part of the PHP LDAP client so that you can perform privileged directory lookups, but I don't know if it would ever be necessary to have those credentials to test that a user could log into the server. 

Somebody added the fields to the LDAP plugin between the time my predecessor left and I began, so I don't know their motivation. I left them in the Central Auth plugin, but now I'm thinking it may be easiest to remove the fields to avoid the storage issue entirely. I'll track down who originally submitted the patch, and see if they are using those fields.

**Comment by lfarrell** [comment]
Okay, thanks for all your help.  I'll let you know if I think of any other ways to save the password.

**Comment by kloor** [comment]
Since it is now clear that the bind credentials are being used, I've given more thought to storage. I'm thinking about adding a field to the config form that allows the user to specify a path to an .ini file. If that path is specified, the plugin options are loaded from that .ini file, and the options from the config form are ignored. This would remove unencrypted passwords from the database, and the file could be stored outside of the web root, but the plugin wouldn't have to be concerned about writing the file.

**Comment by lfarrell** [comment]
@kloor Thanks for the quick fix.  The update works great.

**Comment by bpb54321** [comment]
@kloor Did you ever implement the .ini solution that you specified on March 25, 2015 (see quote below)? I work at Georgetown University and we are interested in not having our LDAP password stored in plain text in the database.

> Since it is now clear that the bind credentials are being used, I've given more thought to storage. I'm thinking about adding a field to the config form that allows the user to specify a path to an .ini file. If that path is specified, the plugin options are loaded from that .ini file, and the options from the config form are ignored. This would remove unencrypted passwords from the database, and the file could be stored outside of the web root, but the plugin wouldn't have to be concerned about writing the file.

**Comment by kloor** [comment]
@bpb54321 I've not worked on this issue, sorry. Pull requests are always welcome.

**Comment by kloor** [comment]
Closed with PR #14.
