### ISSUE TITLE
Implementation with Omeka S

### ISSUE THREAD

**Issue by iamkylemorgan** [BGSU-LITS/omeka-plugin-CentralAuth#13]
Is this plugin adaptable for use with Omeka S?

**Comment by kloor** [comment]
This plugin will not be usable with Omeka S. I currently do not have any plans to work on that until our library decides if it wants to use Omeka S.

Some of the code may potentially be reused to create a Omeka S Module. If you pursue development yourself, feel free to ask me any questions about the existing plugin. Otherwise, sorry I couldn't be of further help.

**Comment by Daniel-KM** [comment]
Hi,

There is no central auth module for Omeka S yet, but there is already a ldap. See https://daniel-km.github.io/UpgradeToOmekaS/omeka_s_modules.html.

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management

**Comment by kloor** [comment]
Closing older issues that did not receive any follow-up.
