### ISSUE TITLE
Advice on creating adaptor for use with ADFS/Azure via simplesamlphp 

### ISSUE THREAD

**Issue by ianchan** [BGSU-LITS/omeka-plugin-CentralAuth#16]
Hi,
Our parent institution is centralized on ADFS (and soon to be Azure) authentication and I have some experience with a custom web app where I've used simpleSAMLphp. I'm hoping that I might be able to leverage your work to add ADFS as an option to this plugin.  Do you have any advice on whether and how to proceed?

Thank you,
Ian

**Comment by kloor** [comment]
Hello Ian,

I did attempt to write the plugin in such a way that other auth methods could be added. Omeka is based on Zend Framework 1, and different types can be added to that framework's [Zend_Auth package](https://framework.zend.com/manual/1.12/en/zend.auth.html) through the use of Adapter classes. 

Omeka itself provides a [Login Adapter Filter](https://omeka.readthedocs.io/en/latest/Reference/filters/login_adapter.html) for plugins where you can return which Adapter should be used to authenticate a user. This filter only authenticates but does not handle existing sessions or logging out. So I found it only usable for a [LdapAdapter](https://github.com/BGSU-LITS/omeka-plugin-CentralAuth/blob/master/adapters/LdapAdapter.php) just for authenticating the initial login.

For the [CasAdapter](https://github.com/BGSU-LITS/omeka-plugin-CentralAuth/blob/master/adapters/CasAdapter.php), I ended up extending Omeka's UserController to more fully utilize the Zend_Auth adapters. The [_getAdapter()](https://github.com/BGSU-LITS/omeka-plugin-CentralAuth/blob/master/controllers/UsersController.php#L250) method in that class is where the plugin obtains the correct adapter based on the settings.

You'll likely want to make an adapter similar to the CasAdapter but with your own backend. It's been a few years, but I remember the biggest issue I had was dealing with PHP's session mechanism. Omeka sets up items in the session before any auth happens, but one of the CAS libraries I was working with would always clear the entire session upon instantiation. I ultimately went with a different library to avoid that issue. I am not familiar enough with the simpleSAMLphp project to know if this may be an issue for you.

Feel free to post again or otherwise contact me if you have any questions, and good luck with your project. I'll be happy to add anything you come up with to this plugin.

**Comment by ianchan** [comment]
Thank you, John. The information you provide is super helpful and apologies for not responding sooner. I'm just starting to look into adding an adaptor. I'll close this issue and open a new one if I run into specific roadblocks.
