### ISSUE TITLE
Can this module handle authorization in addition to authentication?

### ISSUE THREAD

**Issue by kanarb** [BGSU-LITS/omeka-plugin-CentralAuth#6]
I've implemented this module on a test Omeka site and it seems to work great, however, it looks like the authorization needs to be handled within the application rather than through LDAP groups. Is there a way to handle LDAP authorization through this module?

**Comment by kloor** [comment]
This plugin was designed to only provide authentication. Replacing Omeka's built-in authorization system would likely be complicated. Omeka only authenticates users with their credentials upon their first login, and afterwords uses a session stored in the database. You would have to create user accounts upon the first login from an LDAP user.

To authorize users, there would need to be a way to provide a mapping between LDAP groups and Omeka roles. The user's role would have to be updated in the database each time they login. A potential issue is that their session could persist even after their authorization was revoked in LDAP.

If you were interested in developing this, I would suggest altering adapters/LdapAdapter.php around line 51 to update the user's role if an account already exists, or create a new account otherwise. The CentralAuth_LdapAdapter class extends Zend_Auth_Adapter_Ldap, which should be able to provide group information.

**Comment by kanarb** [comment]
Thanks for the info. I'll look into it.
- Bryn

**Comment by kloor** [comment]
Closing older issues that did not receive any follow-up.
